apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  labels:
    app: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: order:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: APPLICATION_PORT
              value: "8080"
            - name: DATA_SOURCE_URL
              value: "root:password@tcp(mysql:3306)/order?parseTime=true"
            - name: ENV
              value: "prod"
            - name: PAYMENT_SERVICE_URL
              value: "payment:8081"
            - name: SHIPPING_SERVICE_URL
              value: "shipping:9090"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: order
spec:
  selector:
    app: order
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP