apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  labels:
    app: shipping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping
  template:
    metadata:
      labels:
        app: shipping
    spec:
      containers:
        - name: shipping
          image: shipping:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 9090
          env:
            - name: APPLICATION_PORT
              value: "9090"
            - name: DATA_SOURCE_URL
              value: "root:password@tcp(mysql:3306)/shipping?parseTime=true"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: shipping
spec:
  selector:
    app: shipping
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: ClusterIP